src/rpt2_acoustics_ptwise.f90

Typo in transverse acoustics point-wise solver.

Fix wrong bmasdq assignment

---

src/rp1_acoustics_variable_ptwise.f90
src/rp1_burgers_ptwise.f90
src/rp1_ptwise.f90
src/rpn2_advection_ptwise.f90
src/rpn2_vc_advection_ptwise.f90
src/rpt2_acoustics_ptwise.f90
src/rpt2_advection_ptwise.f90
src/rpt2_vc_advection_ptwise.f90

rpn2_vc_advection_ptwise and rpt2_vc_advection_ptwise solvers working correctly on annulus examples in both classic and amrclaw repositories, but giving different results from the old Riemann solvers for the swirl example in the amrclaw repository.

Various point-wise Riemann solvers

---

src/riemann_tools.py

Stacking the plots vertically seems helpful since they all share the same x-axis anyway.  The default is still to put them side-by-side.
See plots near the end of http://nbviewer.ipython.org/gist/ketch/445f886de2d09c763f1b for examples of how this looks (and how to call it).

Add vertical layout option and variable names usage to riemann_tools.

---

src/geoclaw_riemann_utils.f

Some modifications proposed by Wenwen Li to deal with sonic point better and to properly handle transverse velocities.  I've been using this version on several problems recently and it seems fine, and works better in some cases.  
Note: These changes will cause some geoclaw regression tests to fail, so the regression data should be updated in geoclaw.
This may help with certain instability issues as in clawpack/geoclaw#209.
Some notes from her email to me:
---
GeoClaw uses the same threshold value ‘criticaltol’ for all criteria; however, ‘s1s2bar’ and ‘s1s2tilde’ have the unit of (m/s)^2, and sE1, sE2, s1m, s2m, uL and uR have the unit of m/s. So I think it might be better to use different threshold values for different lines. I propose to set the threshold values based on the value of …

Update to JCP GeoClaw Riemann solver

---

src/rp1_traffic_vc.f90
src/rp1_traffic_vc_tracer.f90

Third time's a charm!
@rjleveque pointed out that my modifications to the variable-speed traffic solvers in #119 were not all correct.  This changes those solvers back to using f-waves while still including the minor bugfixes.
There is a small glitch with these solvers that seems to affect a single cell near the sonic point of a rarefaction and does not go away on refinement of the mesh.  This is perhaps expected (based on experience with Burgers) for the first-order algorithm, but not for the second-order algorithms.  Our best guess after some discussion is that since the wave speed is ~1.e-16 there, in the f-wave approach the wave nearly vanishes, which causes the limiter to essentially impose the first-order method near that point.  This glitch does go away if one uses the higher-order …

Switch back to using f-waves in variable-speed traffic solvers.

---

src/nonlinear_elasticity_1D_py.py

This adds an option to use a quadratic stress-strain relation in the Python version (only) of the nonlinear elasticity solver.  Previously the only relation available was exponential, which is still the default.  I'm using the quadratic relation for a chapter in the Riemann solvers book.
The choice of which relation to use is controlled by setting `state.problem_data['stress relation']` to either `exponential` (default) or `quadratic`.
The solver could be adapted to other relations without modifying this file by just overriding `sigma()` and `sigmap()`.

Quadratic stress-strain relation in Python elasticity solver

---

src/rp1_traffic_vc.f90
src/rp1_traffic_vc_tracer.f90

For piecewise constant initial data with certain special jumps,
the previous code led to an artificially small estimate of the
CFL number (and consequently, an excessively large initial step size).
This change still avoids division by zero and also avoids the
aforementioned behavior.

Avoid artificially small CFL numbers in traffic_vc solver.

---

src/rp1_traffic_vc.f90
src/rp1_traffic_vc_tracer.f90

This is the same as what is done in rp1_burgers.f90.

Use simple average of wavespeeds for 2nd-order term in traffic solvers.

---

src/geoclaw_riemann_utils.f
src/rpn2_geoclaw.f
src/rpn2_layered_shallow_water.f90
src/rpt2_layered_shallow_water.f90

Add the gradient of pressure into the Riemann solver calculation rather than in the source term splitting.  This has important advantages when considering strong pressure gradients but also leads to significant speeds up to codes that use pressure gradient forcing (e.g. storm surge).
The corresponding GeoClaw PR is clawpack/geoclaw#242.

Include pressure gradient source term in GeoClaw into Riemann Solver

---

src/geoclaw_riemann_utils_vec.f90
src/rpn2_geoclaw_vec.f90
src/rpt2_geoclaw_vec.f90

These changes introduce new vectorized implementations for the single-layer shallow water equations (chile2010 example). The user can easily switch between the serial and the vectorized code: to use vectorization, one needs to define GEOCLAW_VEC=1 before compiling. More info in the chile2010 Makefile.

Added vectorized Riemann solvers for the single-layer shallow water equations

---

src/geoclaw_riemann_utils.f

Since the augmented geoclaw solver includes delh as well as delphi, the jump in
atmospheric pressure must be used to modify this component as well when
doing a well-balanced Riemann solve.
@mandli:  @mjberger and I discovered that the incorporating atmospheric pressure into the well-balanced Riemann solver does not maintain the steady state in which B=0, u=v=0, and 
h = -B - p/(rho*g), 
e.g. with a Gaussian hump for the atmospheric pressure p.  This should be an exact numerical steady state if h in each cell is set this way based on a static pressure prescribed in `aux(pressure_index,:,:)`.   We tracked this down to needing the modification proposed here.  
Note that in equation (44) of the [JCP paper](https://doi.org/10.1016/j.jcp.2007.10.027) by @dlgeorge,  the `delh` is modified by …

geoclaw solver must incorporate delP in deldelh

---

src/euler_roe_solver_mapgrid.f90
src/rpn2_euler_mapgrid.f90
src/rpt2_euler_mapgrid.f90

The value of gamma wasn't getting passed to the Riemann solver because the Python code assumes the common block is named `cparam` but in these solvers it was named `param`.  This is a particularly fragile part of PyClaw and any suggestions for making it more robust would be welcome.  In the meantime, this fixes this case and I couldn't find any other problems of this kind among all the existing Riemann solvers.

Use 'cparam' instead of 'param' for the common block.

---

.travis.yml

Because we use PyClaw for tests and PyClaw imports Visclaw imports matplotlib.

Install matplotlib on Travis.

---

riemann/shallow_roe_tracer_1D_constants.py

Thanks to Daria Bolbot for catching this bug.

In 1D shallow water equations with tracer, tracer index should be 2 (not 3).

---

src/rpn2_geoclaw_adjoint_qwave.f90
src/rpt2_geoclaw_adjoint_qwave.f90

Moved two adjoint Riemann solvers for shallow water equations to this repository from geoclaw/src/2d/shallow, last updated in https://github.com/clawpack/geoclaw/commit/223ee2a22a4c69a5ca19dc073e6c3296170ccbda

Move adjoint riemann solvers

---

src/rp1_mhd_roe.f90

I've updated `rp1_mhd_roe.f90` to use `implicit none` while trying to debug an issue with uninitialized ghost cells when using sharpclaw. @ketch will open an issue for that.

MHD Roe fix

---

src/rpn2_vc_acoustics.f90
src/rpn2_vc_acoustics_adjoint.f90

Need to use auxr(:,i-1) not auxl(:,i-1) in both forward and adjoint solvers.
Bug showed up in testing updated adjoint problem examples for paper:
bad ghost cell values propagate inwards.

fix rpn2_vc_acoustics codes to use auxr

---

src/rpt2_geoclaw.f

Various issues were found in trying to determine (with @mjberger) why radially-symmetric initial data does not lead to symmetric solutions (to machine accuracy).  This PR has several modifications that might change the results obtained, so **do not merge** until it is more carefully tested and compared with previous results on some real-world problems.
Switch to using Jacobian from left or right state, not Roe average, in determining wave speeds and eigenvectors.
The original used `ql, qr` to compute Roe averages, but since the transverse solver splits up a left-going `asdq` (if `imp==1`) or a right-going `asdq` (if `imp==2`) into up-going and down-going components, there is not good justification for using the state from the other side of the normal solve that generated `asdq`.  Now it …

Modifications to rpt2_geoclaw 

---

src/rp1_shallow_hlle.f90

When running a 1D dam-break simulation with a initial near-dry state, the HLLE solver gave a wrong solution. The following image corresponds to the output of hl=1, hr=1e-33, ul=ur=0, using the Classic solver with mx=4000 and order=1:
This seems to be caused by the denominator (s1-s2) getting close to zero while computing middle states. The proposed fix just sets the speeds and waves as zero whenever both hl and hr are smaller than a tolerance (1e-14). This is the output with the same initial values after applying the changes:

Fix for problem with HLLE and near-dry states

---

riemann/euler_1D_py.py

Just a minor typo I noticed when preparing lectures: the equation of state needs to relate pressure to energy, not energy to itself

typo fix in docs: eqn of state has pressure and energy

---

riemann/meson.build

This is only a minor cleanup, it doesn't change behavior. Adding the dependency isn't necessary since Meson 0.63:
https://mesonbuild.com/Release-notes-for-0-63-0.html#python-extension-modules-now-depend-on-the-python-library-by-default
Cleanup is the same as for `pyclaw` here: https://github.com/clawpack/pyclaw/pull/722

Remove the py_dep dependency from extension modules in riemann/meson.build

---

src/geoclaw_riemann_utils.f
src/rpn2_geoclaw.f

Need to initialize wave components 4:5 to 0 for Boussinesq code to work properly, and also pass `meqn,mwaves` rather than `3,3` to `riemann_aug_JCP`.
There will also be a geoclaw PR to point to these updated solvers in `Makefile.bouss`.

update rpn2_geoclaw, geoclaw_riemann_utils

---

riemann/__init__.py
riemann/meson.build

The modules `euler_mapgrid_3D` and `mappedGrid` are built at installation.
`euler_mapgrid_3D` is compiled from 'rpn3_euler_mapgrid.f90', `rpt3_euler_mapgrid.f90`, and `rptt3_euler_mapgrid.f90`, and `mappedGrid` from `euler3d_mappedGrid.f90`.
These changes are discussed in clawpack/pyclaw#721 and clawpack/pyclaw#723.

Compile RS for Euler with gravity at installation

---

src/rpn2_shallow_bathymetry_fwave.f90

In the shallow water fwave solver the final loop over the waves is missing a negative sign.  As is the `if` statement was never reaching the case where the speed $s_k = 0$ and splitting the wave $\mathcal{Z_k}$ into both $\mathcal{A}^\pm \Delta Q$.

Add missing `-` from fluctuation loop

---

src/geoclaw_riemann_utils.f
src/rpn2_geoclaw.f

fixed bug: fw(3,3)--> fw(3,2) in augJCP solver, confirmed for kyles vorticity problem

fix to geoclaw riemann solver for convergence rate test
